---
driver: docker
driver_config:
  use_sudo: false
  forward: 3000:3000

platforms:
  - name: centos-6.6
    driver_config:
      dockerfile: Dockerfile

provisioner:
  name: salt_solo
  formula: gogs
  state_top:
    base:
      '*':
        - gogs
  pillars:
    top.sls:
      base:
        '*':
          - gogs
    gogs.sls:

suites:
  - name: default
  - name: config
    provisioner:
      pillars:
        gogs.sls:
          gogs:
            host: gogs.local
