---
driver: docker
driver_config:
  use_sudo: false
  forward: 3000:3000

platforms:
  - name: centos-6.6
    driver_config:
      dockerfile: Dockerfile

provisioner:
  name: salt_solo
  formula: gogs
  state_top:
    base:
      '*':
        - gogs

suites:
  - name: default
